more parallel

diff --git a/.github/workflows/coolstore-test.yml b/.github/workflows/coolstore-test.yml
--- a/.github/workflows/coolstore-test.yml
+++ b/.github/workflows/coolstore-test.yml
@@ -31,9 +31,8 @@ jobs:
     needs: setup
     runs-on: ubuntu-latest
     strategy:
-      max-parallel: 10
+      max-parallel: 20
       matrix:
-        test-number: [1, 2, 3, 4, 5]
         test-repo:
           - konveyor-ecosystem/coolstore
           - chamilad/tomcat-hello-world
@@ -53,6 +52,7 @@ jobs:
           - Azure/wildfly-container-quickstart
           - agoncal/agoncal-application-petstore-ee7
           - colinbut/monolith-enterprise-application
+        test-number: [1, 2, 3, 4, 5]
       fail-fast: false
     
     steps:
@@ -107,16 +107,6 @@ jobs:
           RUN_NAME="$REPO_NAME_WITHOUT_SLASH-${{ matrix.test-number }}"
           echo "Running container-copilot generate for test $RUN_NAME ..."
           container-copilot generate . > "logs/run-${RUN_NAME}.log" 2>&1
-          
-          # Check if the success message is in the log file
-          if grep -q "$SUCCESS_MESSAGE" "logs/run-${RUN_NAME}.log"; then
-            echo "✅ Test Run $RUN_NAME PASSED - Found '$SUCCESS_MESSAGE'"
-            echo "result=success" >> $GITHUB_OUTPUT
-          else
-            echo "❌ Test Run $RUN_NAME: FAILED - Did not find '$SUCCESS_MESSAGE'"
-            echo "result=failure" >> $GITHUB_OUTPUT
-          fi
-          
           # Save the files it created for successful tests
           if [ -f "Dockerfile" ] || [ -d "manifests" ]; then
             mkdir -p artifacts
@@ -126,6 +116,16 @@ jobs:
 
           #Output the run name for the next step
           echo "run_name=$RUN_NAME" >> $GITHUB_OUTPUT
+          
+          # Check if the success message is in the log file
+          if grep -q "$SUCCESS_MESSAGE" "logs/run-${RUN_NAME}.log"; then
+            echo "✅ Test Run $RUN_NAME PASSED - Found '$SUCCESS_MESSAGE'"
+            echo "result=success" >> $GITHUB_OUTPUT
+          else
+            echo "❌ Test Run $RUN_NAME: FAILED - Did not find '$SUCCESS_MESSAGE'"
+            echo "result=failure" >> $GITHUB_OUTPUT
+            exit 1
+          fi
 
       - name: Upload test artifacts
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
@@ -137,6 +137,7 @@ jobs:
 
       - name: Upload test logs
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+        if: always()
         with:
           name: container-copilot-logs-${{ steps.run_test.outputs.run_name }}
           path: test-repo/logs/
